
VERSION_PRODUCT		= Policy Controller for Microsoft Windows
VERSION_MAJOR		= 8
VERSION_MINOR		= 4

COMPILER=VS2008
PLATFORMSDK=7.0

CSSUBTARGET = NextLabs.CSCInvoke

SRC = \
 	AssemblyInfo.cs \
	CSCInvoke.cs
