#ifndef _DSNTPROCIOCTL_H_
#define _DSNTPROCIOCTL_H_	1

#include "dstypes.h"
#ifndef _NTIFS_
#include <winioctl.h>
#endif	//#ifndef _NTIFS_

#define DSNTPROC_W32_DEVICE_NAME			L"\\\\.\\NTProcDrv"
#define DSCORE_W32_DEVICE_NAME				L"\\\\.\\DSCORE"
#define FILE_DEVICE_UNKNOWN					0x00000022
#define IOCTL_UNKNOWN_BASE					FILE_DEVICE_UNKNOWN
#define IOCTL_NTPROCDRV_GET_PROCINFO		CTL_CODE(IOCTL_UNKNOWN_BASE, 100, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_NTPROCDRV_GET_IMAGEINFO		CTL_CODE(IOCTL_UNKNOWN_BASE, 101, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_NTPROCDRV_RESET_INJEVENT		CTL_CODE(IOCTL_UNKNOWN_BASE, 102, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_NTPROCDRV_GET_FILE_INFO		CTL_CODE(IOCTL_UNKNOWN_BASE, 103, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_NTPROCDRV_REGISTER_RECOVERY	CTL_CODE(IOCTL_UNKNOWN_BASE, 104, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_NTPROCDRV_UNREGISTER_RECOVERY	CTL_CODE(IOCTL_UNKNOWN_BASE, 105, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)

#endif	//#ifndef _DSNTPROCIOCTL_H_