#!/bin/bash
#
# DESCRIPTION
#	Invoke PCV build
#
# USAGE:
#	Steps to invoke this script.
#		export NLEXTERNALDIR=<path>
#		export BUILD_NUMBER=<#>
#		source ./setEnv
#		./buildPcv
#
# HUDSON BUILD:
#	cd $WORKSPACE/D_SiriusR2
#	export NLEXTERNALDIR=c:/hudson/jobs/external_latest/workspace/external
#	source ./setEnv
#	./buildPcv
#
# Build Options:
#	Note that you can specific installer target (i.e., install_*) without specifying compile
#	targets first (i.e., pc, kmc, wde or devtools). However, it is easier to understand if
#	we specify compile targets before installer targets.
#
#	make -f build/Makefile.compile || exit $?
#	make -f build/Makefile.compile compile_pc compile_kmc compile_lme compile_ne compile_oce compile_oe compile_rde compile_se compile_wde compile_devtool install_pc install_kmc install_lme install_ne install_oce install_oe install_rde install_se install_wde install_support || exit $?
#
# Publish Options:
#	Note that target "pc" refers to publishing PC installers. It should only be called
#	after calling install/pc/buildInstaller at this time. Here is a quick summary of
#	definition popular targets:
#		wde: wde_local wde_sync
#		pc: pc_local pc_sync
#		support: sdk reskit
#		archive: archive_bin archive_xlib archive_symbol archive_install
#
#	make -f build/Makefile.publish TYPE=pcv || exit $?
#	make -f build/Makefile.publish TYPE=pcv kmc lme ne oce oe rde se wde pc support archive || exit $


LOG_FILE=buildPcv.log
BUILD_MANIFEST_FILE=build.manifest

(
set -x
# Extract Perforce Workspace and Hudson info (only if running on Hudson)
if [ -f ../config.xml ]; then
	build/getGitWorkspaceInfo.pl ../config.xml
fi

# Prepare environment
./configure --type=pcv_smdc --mapBuildRoot=g || exit $?
source build.config

# Prepare dependencies
make -f build/Makefile.xlib
chmod -R ug+w xlib

# Compile code and build installers
make -f build/Makefile.compile install_pcoewde || exit $?

# Publish packages and artifacts to BODA only if PUBLISH_TO_BODA environment variable is set
if [ "X${PUBLISH_TO_BODA}" = "XYes" -o "X${PUBLISH_TO_BODA}" = "Xyes" -o "X${PUBLISH_TO_BODA}" = "XYES" -o "X${PUBLISH_TO_BODA}" = "X1" ]
then
	# Publish installers and artifacts
	make -f build/Makefile.publish TYPE=pcv pcoe archive archive_install_small || exit $?
fi

# Create and publish build manifest
build/createBuildManifest.pl $LOG_FILE > $BUILD_MANIFEST_FILE || exit $?

# Publish build-manifest to BODA only if PUBLISH_TO_BODA environment variable is set
if [ "X${PUBLISH_TO_BODA}" = "XYes" -o "X${PUBLISH_TO_BODA}" = "Xyes" -o "X${PUBLISH_TO_BODA}" = "XYES" -o "X${PUBLISH_TO_BODA}" = "X1" ]
then
	make -f build/Makefile.publish TYPE=pcv manifest || exit $?
fi

set +x

echo
echo
echo "####################### BUILD MANIFEST CONTENTS ########################"
cat ${WORKSPACE}/${BUILD_MANIFEST_FILE}
echo "########################################################################"
) 2>&1 | tee $LOG_FILE

exit ${PIPESTATUS[0]}
