/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bluejungle_framework_utils_NetworkUtils */

#ifndef _Included_com_bluejungle_framework_utils_NetworkUtils
#define _Included_com_bluejungle_framework_utils_NetworkUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bluejungle_framework_utils_NetworkUtils
 * Method:    getServerList
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_bluejungle_framework_utils_NetworkUtils_getServerList
  (JNIEnv *, jclass);

/*
 * Class:     com_bluejungle_framework_utils_NetworkUtils
 * Method:    getSharedFolderList
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_bluejungle_framework_utils_NetworkUtils_getSharedFolderList
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
