// CE_Explorer.idl : IDL source for CE_Explorer
//

// This file will be processed by the MIDL tool to
// produce the type library (CE_Explorer.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(09A48212-1DDA-4BC8-8A7E-6C3DA6C3541B),
	helpstring("ICOEShell Interface"),
	pointer_default(unique)
]
interface ICOEShell : IUnknown{
};
[
	uuid(7949C60D-35D5-40F5-B09E-03F4DDF82AD9),
	version(1.0),
	helpstring("CE_Explorer 1.0 Type Library")
]
library CE_ExplorerLib
{
	importlib("stdole2.tlb");
	[
		uuid(38B14C4F-31AE-468B-8BD2-DCB57645074A),
		helpstring("COEShell Class")
	]
	coclass COEShell
	{
		[default] interface ICOEShell;
	};
};
