//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by msoPEP.rc
//
#define IDS_PROJNAME                    100
#define IDR_MSOPEP                      101
#define IDR_MSOOBJ                      102
#define IDR_INSPSEVENTDISP              103
#define IDR_INSPEVENTDISP               104
#define IDR_ITEMEVENTDISP               105
#define IDD_DENYLISTDLG                 106
#define IDD_HDRDLG                      107
#define IDC_BUTTON_OK                   200
#define IDC_LIST_DENY                   201
#define IDC_HDAREA                      202
#define IDC_FILEPATH                    203
#define IDC_DESC                        204
#define IDC_WARNING                     205
#define IDC_BTN_RMA1                    209
#define IDC_BTN_RMA2                    210
#define IDC_BTN_RMA3                    211
#define IDC_BTN_RMA4                    212
#define IDC_BTN_RMA5                    213
#define IDC_BTN_RMA6                    214
#define IDC_BTN_RMA7                    215
#define IDC_ICONINFO                    216
#define IDC_CELLICON1                   217
#define IDC_CELLICON2                   218
#define IDB_BITMAP1                     218
#define IDC_CELLICON3                   219
#define IDC_CELLICON4                   220
#define IDC_CELLICON5                   221
#define IDI_ICON1                       221
#define IDC_CELLICON6                   222
#define IDC_CELLICON7                   223
#define IDC_ICONWRONG1                  224
#define IDC_ICONWRONG2                  225
#define IDC_ICONWRONG3                  226
#define IDC_ICONWRONG4                  227
#define IDC_ICONWRONG5                  228
#define IDC_ICONWRONG6                  229
#define IDC_ICONWRONG7                  230
#define IDC_TITLE1                      231
#define IDC_TITLE2                      232
#define IDC_TITLE3                      233
#define IDC_TITLE4                      234
#define IDC_TITLE5                      235
#define IDD_PADLG                       235
#define IDC_TITLE6                      236
#define IDD_PAVIEWDLG                   236
#define IDC_TITLE7                      237
#define IDD_PAVIEWITEM                  237
#define IDC_RESULT1                     238
#define IDD_DLGYELED                    238
#define IDC_RESULT2                     239
#define IDD_ALERT_MESSAGE_BOX           239
#define IDC_RESULT3                     240
#define IDC_RESULT4                     241
#define IDC_RESULT5                     242
#define IDC_RESULT6                     243
#define IDC_RESULT7                     244
#define IDC_ICONFAIL1                   245
#define IDC_ICONFAIL2                   246
#define IDC_ICONFAIL3                   247
#define IDC_ICONFAIL4                   248
#define IDC_ICONFAIL5                   249
#define IDC_ICONFAIL6                   250
#define IDC_ICONFAIL7                   251
#define IDD_PROGRESSDLG                 253
#define IDC_SENDEMAIL                   253
#define IDC_DIPTITLE                    254
#define IDC_REMOVE                      254
#define IDC_DIPPROG                     255
#define IDC_CANCEL                      255
#define IDC_DIPCANCEL                   256
#define IDC_EXTMAIL                     256
#define IDD_DI2K3DLG                    257
#define IDC_NOTIFY                      257
#define IDC_BTN_REMOVEALL               258
#define IDC_HORZETCHED                  258
#define IDC_INSPECTLIST                 259
#define IDC_MULTICLIENT                 259
#define IDC_LIST1                       260
#define IDC_MULTIUSER                   260
#define IDB_CROSSARROW                  261
#define IDC_MULTICLIENTDESC             261
#define IDB_USERSGROUP                  262
#define IDC_MULTIUSERDESC               262
#define IDB_WORDICON                    263
#define IDC_ITEMMULTIUSER               263
#define IDB_EXECICON                    264
#define IDC_ITEMMULTICLIENT             264
#define IDB_PWPTICON                    265
#define IDC_ITEMRECIPIENT               265
#define IDB_PDFICON                     266
#define IDC_ITEMFILEICON                266
#define IDB_UNKNOWN                     267
#define IDC_ITEMHIDESHOW                267
#define IDI_MAIN                        268
#define IDC_ITEMCHECK                   268
#define IDI_EXTERNALMAIL                269
#define IDC_ITEMCOMBO                   269
#define IDI_CROSSARROW                  270
#define IDC_BUTTON2                     270
#define IDC_ITEMREMOVE                  270
#define IDI_USERSGROUP                  271
#define IDC_WMSG                        271
#define IDC_JSTATIC                     272
#define IDC_WJUST                       273
#define IDC_VIOSTATIC                   274
#define IDC_YHORZETCHED                 275
#define IDC_SYELED4                     276
#define IDC_YMAIL                       277
#define IDC_STATIC_HEADER               278
#define IDC_STATIC_FOOTER               279
#define IDC_STATIC_TIP                  282
#define IDD_OE_WARNING_BOX              133
#define IDC_STATIC_MESSAGE              1004
#define IDC_STATIC_ACTION_DESC          1005
#define IDC_TIP_ICON                    1006
#define IDC_LIST_MESSAGE                1007
#define IDB_ALERT_CROSS					1008
#define IDB_ALERT_WARN					1009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        240
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         278
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
