/********************************************************************************************
 *
 * I/O control codes for NLCC
 *
 *******************************************************************************************/

#ifndef __NLCC_IOCTL_H__
#define __NLCC_IOCTL_H__

#define IOCTL_POLICY_REQUEST \
    CTL_CODE (FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_POLICY_RESPONSE \
    CTL_CODE (FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SET_CM_READY \
    CTL_CODE (FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ADD_PROTECTED_PID \
    CTL_CODE (FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DEL_PROTECTED_PID \
    CTL_CODE (FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_PROTECTED_PIDS \
    CTL_CODE (FILE_DEVICE_UNKNOWN, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CLR_PROTECTED_PIDS \
    CTL_CODE (FILE_DEVICE_UNKNOWN, 0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_POLICY_QUERY \
    CTL_CODE (FILE_DEVICE_UNKNOWN, 0x808, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif /* __NLCC_IOCTL_H__ */
