/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bluejungle_destiny_agent_controlmanager_PDPJni */

#ifndef _Included_com_bluejungle_destiny_agent_controlmanager_PDPJni
#define _Included_com_bluejungle_destiny_agent_controlmanager_PDPJni
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: COMP_INFO */
/*
 * Class:     com_bluejungle_destiny_agent_controlmanager_PDPJni
 * Method:    SendPolicyResponse
 * Signature: (JLjava/lang/String;J[Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_bluejungle_destiny_agent_controlmanager_PDPJni_SendPolicyResponse
  (JNIEnv *, jobject, jlong, jstring, jlong, jobjectArray);

/*
 * Class:     com_bluejungle_destiny_agent_controlmanager_PDPJni
 * Method:    SendServiceResponse
 * Signature: (JLjava/lang/String;[Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_bluejungle_destiny_agent_controlmanager_PDPJni_SendServiceResponse
  (JNIEnv *, jobject, jlong, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
